# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('start', models.DateTimeField(verbose_name='date published')),
                ('end', models.DateTimeField(verbose_name='date published')),
                ('all_day', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
    ]
