# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='end',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='calender',
            name='start',
            field=models.CharField(max_length=50),
        ),
    ]
