# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0004_calender_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calender',
            name='id',
        ),
        migrations.AlterField(
            model_name='calender',
            name='event_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
