# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0006_calender_event_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='event_google_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
