# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 05:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0008_calender_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 2, 5, 24, 45, 954569, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='calender',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='calender',
            name='end_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='calender',
            name='start_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
