# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0009_auto_20170202_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 19, 18, 13, 25, 408015, tzinfo=utc)),
        ),
    ]
